//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XR.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Graphics : global::System.Configuration.ApplicationSettingsBase {
        
        private static Graphics defaultInstance = ((Graphics)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Graphics())));
        
        public static Graphics Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TexQualityBias {
            get {
                return ((int)(this["TexQualityBias"]));
            }
            set {
                this["TexQualityBias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int TextureFilter {
            get {
                return ((int)(this["TextureFilter"]));
            }
            set {
                this["TextureFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseMips {
            get {
                return ((bool)(this["UseMips"]));
            }
            set {
                this["UseMips"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int MultiSampling {
            get {
                return ((int)(this["MultiSampling"]));
            }
            set {
                this["MultiSampling"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int LightingQuality {
            get {
                return ((int)(this["LightingQuality"]));
            }
            set {
                this["LightingQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BackFaceCulling {
            get {
                return ((bool)(this["BackFaceCulling"]));
            }
            set {
                this["BackFaceCulling"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int OutputBrightness {
            get {
                return ((int)(this["OutputBrightness"]));
            }
            set {
                this["OutputBrightness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string RenderingBackend {
            get {
                return ((string)(this["RenderingBackend"]));
            }
            set {
                this["RenderingBackend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>Resources/Skybox/right.jpg</string>
  <string>Resources/Skybox/left.jpg</string>
  <string>Resources/Skybox/top.jpg</string>
  <string>Resources/Skybox/bottom.jpg</string>
  <string>Resources/Skybox/front.jpg</string>
  <string>Resources/Skybox/back.jpg</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FacesColl {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FacesColl"]));
            }
            set {
                this["FacesColl"] = value;
            }
        }
    }
}
